# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
    - run: echo helloworld
    - name: Single Spa application parse application and package name
      id: parseapplication
      uses: ajaybeniwal/parse-application-name-package-action@v1.0
    # Use the output from the `hello` step
    - name: Get the output time
      run: |
        echo "The product was ${{ steps.parseapplication.outputs.product }}"
        echo "The mfename was ${{ steps.parseapplication.outputs.mfename }}"
        echo "The mfename was ${{ steps.parseapplication.outputs.servicename }}"
        echo "/microfrontends/${{ steps.parseapplication.outputs.product }}/${{ steps.parseapplication.outputs.mfename }}/$GITHUB_SHA/bundle.js"
    - name: Clone another repo
      uses: actions/checkout@v2
      with:
        repository: ajaybeniwal/clone-action-repo
        ref: "master"
        path: ./CloneRepo
    - name: Echo The Build folder
      run: |
        echo "the commimit hash of this build is $GITHUB_RUN_ID and the sha is $GITHUB_SHA"
        ls
        echo "creating json files for the project"
        
